### ISSUE TITLE
Request to change exotic object notation

### ISSUE THREAD

**Issue by dotnetCarpenter** [sanctuary-js/sanctuary-show#14]
Can we please have different representation of Array and Object?

Every time I see `[Left ([object HTMLInputElement])]` I think I have a nested Array but it is in fact `Array (Left ([object HTMLInputElement]))` or perhaps better, `[Left (object HTMLInputElement)]`.

**Comment by davidchambers** [comment]
The goal is for `eval (show (x)) = x` to hold when possible:

```javascript
> const {Just, equals} = require ('sanctuary')

> const show = require ('sanctuary-show')

> (x => equals (x) (eval (show (x)))) (['foo', 'bar', 'baz'])
true

> (x => equals (x) (eval (show (x)))) (Just (42))
true
```

I see no problem with the way arrays are shown:

```javascript
> show (['foo', 'bar', 'baz'])
'["foo", "bar", "baz"]'
```

It seems this is the behaviour you would like to change:

```javascript
> show (document.createElement ('input'))
'[object HTMLInputElement]'
```

`document.createElement ('input')` does not have a `@@show` method, so we fall back to its `toString` implementation:

```javascript
> String (document.createElement ('input'))
'[object HTMLInputElement]'
```

We *could* do something like this:

```javascript
> String (document.createElement ('input'))
'document.createElement ("input")'
```

I am against this approach for several reasons:

  - HTML elements are not values (they are stateful);
  - it ignores the element's attributes (such as `value`); and
  - it would add DOM-specific code to the library.

If you have a different approach in mind, please share it. :)

**Comment by dotnetCarpenter** [comment]
>I see no problem with the way arrays are shown:
>
>```js
> > show (['foo', 'bar', 'baz'])
>'["foo", "bar", "baz"]'
>```

I agree with you that arrays by themselves are not an issue but it is in combination with host/exotic objects, such as DOM elements.

Here is an array with 4 `Either`'s that each contain an array of DOM elements.

```js
var a = document.querySelector('li')
S.show ([S.Left ([a,a,a,a]),S.Right ([a,a]),S.Left ([a]),S.Left ([a,a,a,a])])
```
![[Left ([[object HTMLLIElement], [object HTMLLIElement], [object HTMLLIElement], [object HTMLLIElement]]), Right ([[object HTMLLIElement], [object HTMLLIElement]]), Left ([[object HTMLLIElement]]), Left ([[object HTMLLIElement], [object HTMLLIElement], [object HTMLLIElement], [object HTMLLIElement]])]](https://user-images.githubusercontent.com/43763/113863859-777f5480-97aa-11eb-9cbb-c95aadbf6376.png "[Left ([[object HTMLLIElement], [object HTMLLIElement], [object HTMLLIElement], [object HTMLLIElement]]), Right ([[object HTMLLIElement], [object HTMLLIElement]]), Left ([[object HTMLLIElement]]), Left ([[object HTMLLIElement], [object HTMLLIElement], [object HTMLLIElement], [object HTMLLIElement]])]")

Here is the same where the DOM elements are all HTMLAnchorElement:
```js
var a = document.querySelector('a')
S.show ([S.Left ([a,a,a,a]),S.Right ([a,a]),S.Left ([a]),S.Left ([a,a,a,a])])
```
![[Left ([https://github.com/sanctuary-js/sanctuary, https://github.com/sanctuary-js/sanctuary, https://github.com/sanctuary-js/sanctuary, https://github.com/sanctuary-js/sanctuary]), Right ([https://github.com/sanctuary-js/sanctuary, https://github.com/sanctuary-js/sanctuary]), Left ([https://github.com/sanctuary-js/sanctuary]), Left ([https://github.com/sanctuary-js/sanctuary, https://github.com/sanctuary-js/sanctuary, https://github.com/sanctuary-js/sanctuary, https://github.com/sanctuary-js/sanctuary])]](https://user-images.githubusercontent.com/43763/113864408-29b71c00-97ab-11eb-8a4c-32b48bba37e4.png "[Left ([https://github.com/sanctuary-js/sanctuary, https://github.com/sanctuary-js/sanctuary, https://github.com/sanctuary-js/sanctuary, https://github.com/sanctuary-js/sanctuary]), Right ([https://github.com/sanctuary-js/sanctuary, https://github.com/sanctuary-js/sanctuary]), Left ([https://github.com/sanctuary-js/sanctuary]), Left ([https://github.com/sanctuary-js/sanctuary, https://github.com/sanctuary-js/sanctuary, https://github.com/sanctuary-js/sanctuary, https://github.com/sanctuary-js/sanctuary])]")

The two examples are suppose to highlight that representation matters a great deal in order to understand data structures. This is not limited to the DOM but is the same issue for all environments that are not purely data, namely all environments that contain stateful graphic elements, such as [ReactNative](https://reactnative.dev), [Titanium Mobile](https://titaniumsdk.com), [GNOME Gtk+](https://www.npmjs.com/package/node-gtk) etc.

The literal symbol `[` and `]` has a special meaning which is Array, so if we could remove `[]` from everything that is **not** `Array.isArray()`, we would end up with:

![image](https://user-images.githubusercontent.com/43763/113867945-6edd4d00-97af-11eb-9aa6-ac3adc9501b2.png "[Left ([object HTMLLIElement, object HTMLLIElement, object HTMLLIElement, object HTMLLIElemen]]), Right ([object HTMLLIElement, object HTMLLIElemen]]), Left ([object HTMLLIElemen]]), Left ([object HTMLLIElement, object HTMLLIElement, object HTMLLIElement, object HTMLLIElemen]])]")

I think that is a little easier on the eye.

For these exotic objects `eval (show (x)) = x` will never hold true.

PS. All screen shot are taken from blink devtools with dark theme.

**Comment by davidchambers** [comment]
Current behaviour:

```javascript
> show ([document.createElement ('li'), document.createElement ('li')])
'[[object HTMLLIElement], [object HTMLLIElement]]'
```

Alternative behaviour:

```javascript
> show ([document.createElement ('li'), document.createElement ('li')])
'[<object HTMLLIElement>, <object HTMLLIElement>]'
```

:point_up: What do you think of this approach, @dotnetCarpenter?

**Comment by dotnetCarpenter** [comment]
I like it a lot.


    "[Left ([<object HTMLLIElement>, <object HTMLLIElement>, <object HTMLLIElement>, <object HTMLLIElement>]), Right ([<object HTMLLIElement>, <object HTMLLIElement>]), Left ([<object HTMLLIElement>]), Left ([<object HTMLLIElement>, <object HTMLLIElement>, <object HTMLLIElement>, <object HTMLLIElement>])]"

The arrays above are clear.

In contrast to:

    "[Left ([[object HTMLLIElement], [object HTMLLIElement], [object HTMLLIElement], [object HTMLLIElement]]), Right ([[object HTMLLIElement], [object HTMLLIElement]]), Left ([[object HTMLLIElement]]), Left ([[object HTMLLIElement], [object HTMLLIElement], [object HTMLLIElement], [object HTMLLIElement]])]"
